bt_executer_node:
  ros__parameters:
    bt_xml_file: dice_challenge.xml
    bt_package: drims_homework
    plugins:
      - get_grasp_orientation
      - plan_rotation_path
      - resolve_die_orientation
      - compute_canonical_placement
      - get_tip_rotation
      - compute_relative_rotation
    ros_plugins:
      - dice_identification
      - move_to_pose
      - move_to_joint
      - gripper_command
      - attach_object
      - detach_object
      - get_face_rotation
      - compute_xy_correction
      - check_closing_axis_vertical
      - select_tip_axis
      - capture_frame_rotation
      - allow_attached_contact
